<?php

namespace Database\Seeders;

use App\Models\Eslon;
use App\Models\Layanan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PerihalTagihanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $layanan = Layanan::select('id')->get()->toArray();
        $perihalTagihan = [
            [
                'kode' => '1',
                'hal' => 'Biaya Dokter Sp. Luar (On Call) RS PKT',
                'jenis_tagihan' => 'Dokter',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa konsultasi medis berupa Rincian Pembayaran Atas Tindakan Medis yang dilakukan oleh dokter Sp. tidak tetap.',
                'ket_pembayaran' => 'Biaya',
                'layanan_id' => $layanan[rand(0, count($layanan) - 1)]['id'],
                'status' => 'Anak Sekolah Luar Bontang',
                'unit_dokter' => 'dr. Adi Rizka, SpB',
                'kota' => 'Bontang',
                'rumah_sakit' => 'RS Amalia',
                'spesialisasi' => 'UGD',
                'bank' => 'ANZ PANIN BANK',
                'status' => 'PISA',
                'tindakan' => 'Jasa Dokter'
            ],
            [
                'kode' => '2',
                'hal' => 'Biaya Kerjasama Dokter Sp. Perbantuan Tetap RSUD Bontang',
                'jenis_tagihan' => 'Korespondensi Eksternal',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa konsultasi medis berupa Rincian Pembayaran Atas Tindakan Medis yang dilakukan oleh dokter Sp. perbantuan tetap.',
                'ket_pembayaran' => 'Biaya Berobat',
                'layanan_id' => $layanan[rand(0, count($layanan) - 1)]['id'],
                'status' => 'Perawatan Gigi/Orthodonti',
                'unit_dokter' => 'dr. Alia Shahnaz, SpOG',
                'kota' => 'Samarinda',
                'rumah_sakit' => 'RS PKT',
                'spesialisasi' => 'POLI UMUM',
                'bank' => 'BANK JATIM',
                'status' => 'PROKESPEN',
                'tindakan' => 'JASA DOKTER & RESEP',
            ],
            [
                'kode' => '3',
                'hal' => 'SURAT PERMINTAAN PROSES PEMBAYARAN',
                'jenis_tagihan' => '',
                'deskripsi' => '',
                'ket_pembayaran' => '',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => '',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => '',
                'bank' => '',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '4',
                'hal' => 'Biaya Jasa Perawat Anestesi RSUD Bontang',
                'jenis_tagihan' => 'Laporan Bulanan',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa medis berupa Rincian Pembayaran Atas Tindakan Medis yang dilakukan oleh perawat anestesi.',
                'ket_pembayaran' => 'Biaya Pengganti Pengelolaan Darah',
                'layanan_id' => null,
                'status' => 'Rawat Jalan KLL',
                'unit_dokter' => 'dr. Ariadi Nugraha, SpJP',
                'kota' => '',
                'rumah_sakit' => 'RS Yabis',
                'spesialisasi' => 'MCU',
                'bank' => 'BANK JATENG',
                'status' => '',
                'tindakan' => 'JASA DOKTER, RESEP & LAB',
            ],
            [
                'kode' => '5',
                'hal' => 'PROKESPEN KAPITASI - Penagihan Biaya Berobat PENSIUNAN PT BADAK LNG HOMEBASED BONTANG',
                'jenis_tagihan' => 'Pasien',
                'deskripsi' => '',
                'ket_pembayaran' => '',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => '',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => '',
                'bank' => '',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '6',
                'hal' => 'PENAGIHAN BIAYA KE YAYASAN PROKESPEN',
                'jenis_tagihan' => 'Pasien',
                'deskripsi' => '',
                'ket_pembayaran' => '',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => '',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => '',
                'bank' => '',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '7',
                'hal' => 'REIMBURSEMENT PASIEN PENSIUNAN',
                'jenis_tagihan' => 'Pasien',
                'deskripsi' => '',
                'ket_pembayaran' => '',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => '',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => '',
                'bank' => '',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '8',
                'hal' => 'PENAGIHAN BIAYA KE CSR RS LNG BADAK',
                'jenis_tagihan' => 'Pasien',
                'deskripsi' => '',
                'ket_pembayaran' => '',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => '',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => '',
                'bank' => '',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '9',
                'hal' => 'PENAGIHAN BIAYA KE BPJS KETENAGAKERJAAN',
                'jenis_tagihan' => 'Pasien',
                'deskripsi' => '',
                'ket_pembayaran' => '',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => '',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => '',
                'bank' => '',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '10',
                'hal' => 'Penagihan Biaya oleh RS Non Rekanan dan Tanpa Rujukan untuk Kondisi Kegawatdaruratan',
                'jenis_tagihan' => 'Rekanan',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa konsultasi medis berupa Rincian Pembayaran Atas Konsultasi dan Tindakan Medis yang dilakukan oleh tenaga medis ahli RSUD Taman Husada Bontang.',
                'ket_pembayaran' => 'Pemasangan Gigi Palsu',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Johan Wijaya Kesit',
                'kota' => '',
                'rumah_sakit' => 'RS Restu Ibu',
                'spesialisasi' => 'Sp. Bedah Anak',
                'bank' => 'BPD KALTIM',
                'status' => '',
                'tindakan' => 'FISIOTERAPI',
            ],
            [
                'kode' => '11',
                'hal' => 'Penagihan Biaya Kerjasama Dokter Sp. Perbantuan oleh FK UNAIR',
                'jenis_tagihan' => 'Surat Keterangan Kematian',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa konsultasi medis berupa Rincian Pembayaran Atas Konsultasi dan Tindakan Medis yang dilakukan oleh tenaga medis ahli RSUD Taman Husada Bontang.',
                'ket_pembayaran' => 'Biaya Pembelian Obat',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Meity Ardiana, SpJP',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah Mulut',
                'bank' => 'BRI',
                'status' => '',
                'tindakan' => 'HEMODIALISA',
            ],
            [
                'kode' => '12',
                'hal' => 'Penagihan Biaya ke Perusahaan Lain/ Asuransi Pihak Ke 3',
                'jenis_tagihan' => 'Surat Keterangan Medis',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas Biaya Pendampingan Pasien oleh Tenaga Medis RS Rekanan berupa bukti pembelian tiket penerbangan dan salinan kuitansi transaksi.',
                'ket_pembayaran' => 'Penagihan Biaya',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Primasari, SpJP',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah Orthopedi',
                'bank' => 'CIMB NIAGA',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '13',
                'hal' => 'Penagihan Biaya ke PT. Badak NGL',
                'jenis_tagihan' => 'Surat Keterangan Medis',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayara atas Biaya Pendampingan Pasien oleh Tenaga Medis RS Rekanan berupa bukti pembelian tiket penerbangan dan salinan kuitansi transaksi.',
                'ket_pembayaran' => 'Penagihan Biaya',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Primasari, SpJP',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah Orthopedi',
                'bank' => 'CIMB NIAGA',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '14',
                'hal' => 'Penagihan Biaya ke Asuransi Mandiri Inhealth',
                'jenis_tagihan' => 'Surat Keterangan Medis',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas Biaya Pendampingan Pasien oleh Tenaga Medis RS Rekanan berupa bukti pembelian tiket penerbangan dan salinan kuitansi transaksi.',
                'ket_pembayaran' => 'Penagihan Biaya',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Primasari, SpJP',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah Orthopedi',
                'bank' => 'CIMB NIAGA',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '15',
                'hal' => 'Biaya MCU di RS/Klinik/Dokter Rujukan Non Rekanan',
                'jenis_tagihan' => 'BA Serah Terima Jenazah',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa konsultasi medis dan pemeriksaan penunjang lainnya untuk MCU diluar jobsite berupa Expense Report dan kuitansi transaksi.',
                'ket_pembayaran' => 'Perawat Anestesi RSUD Bontang',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Rien Potu Agustina',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah Plastik',
                'bank' => 'DANAMON',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '16',
                'hal' => 'Biaya Sewa Alat Medis',
                'jenis_tagihan' => 'Visum Et Repertum',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas penyewaaan alat medis milik dokter atau pihak rekanan lainnya untuk tindakan operatif atau lainnya berupa Rincian Penggunaan dan Biaya yang harus dibayarkan.',
                'ket_pembayaran' => 'Perawatan Orthodonti Kasus Baru',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Rini Kustiani',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah Saraf',
                'bank' => 'HSBC',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '17',
                'hal' => 'Biaya Pendampingan Pasien oleh Tenaga Medis',
                'jenis_tagihan' => 'Pekerja dan Keluarga',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas Biaya Pendampingan Pasien oleh Tenaga Medis RS Rekanan berupa bukti pembelian tiket penerbangan dan salinan kuitansi transaksi.',
                'ket_pembayaran' => 'Perawatan Orthodonti ke-1',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Suhardi, SpJP',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah TKV',
                'bank' => 'MANDIRI',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '18',
                'hal' => 'Penagihan Biaya ke SDM RS LNG BADAK',
                'jenis_tagihan' => '',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa konsultasi medis di luar jobsite berupa Surat Jaminan Layanan Kesehatan yang diberikan pada pasien rujukan dokter RS LNG Badak KSO BP.',
                'ket_pembayaran' => 'Perawatan Orthodonti ke-2',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'dr. Tony Widyawan, SpOG',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Bedah Urologi',
                'bank' => 'MEGA',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '19',
                'hal' => 'Tagihan Susulan',
                'jenis_tagihan' => '',
                'deskripsi' => 'Terlampir Dokumen Pendukung Pembayaran atas perkiraan biaya berobat di RS Non Rekanan berdasarkan informasi yang diperoleh via SLJJ dengan petugas admission RS Rujukan Non Rekanan',
                'ket_pembayaran' => 'Perawatan Orthodonti ke-3',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'drg. Atik Suhargiati',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Gigi Prostodonsia',
                'bank' => 'MUAMALAT',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '20',
                'hal' => 'Penagihan Biaya ke BPJS Kesehatan',
                'jenis_tagihan' => '',
                'deskripsi' => 'Terlampir Dokumen Pendukung Pembayaran atas perkiraan biaya berobat di klinik dokter rujukan non rekanan berdasarkan informasi yang diperoleh dari kunjungan berobat sebelumnya di tempat yang sama',
                'ket_pembayaran' => 'Perawatan Orthodonti Lanjutan di',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'drg. Herawati Kusuma',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Jantung dan Pembuluh Darah',
                'bank' => 'OCBC NISP',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '21',
                'hal' => 'Pembayaran Biaya ke Rumah Sakit / Klinik Laboratorium Rekanan',
                'jenis_tagihan' => '',
                'deskripsi' => 'Terlampir dikirimkan Dokumen Pendukung Pembayaran atas jasa pengiriman hasil pemeriksaan penunjang medis berupa tanda terima dan kuitansi.',
                'ket_pembayaran' => 'Persalinan',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'drg. Rio Subi Candra Ditya',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Kedokteran Fisik dan Rehabilitasi',
                'bank' => 'PERMATA',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '22',
                'hal' => 'Pembayaran Biaya ke Perusahaan Rekanan / Pihak Ke-3',
                'jenis_tagihan' => '',
                'deskripsi' => '',
                'ket_pembayaran' => 'Program Bayi Tabung',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'Laboratorium',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Kedokteran Jiwa',
                'bank' => 'RABOBANK',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '23',
                'hal' => 'Penagihan Biaya ke Yayasan RS LNG Badak',
                'jenis_tagihan' => '',
                'deskripsi' => '',
                'ket_pembayaran' => 'Spesimen Laboratorium',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'Medical Check Up (MCU)',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Konservasi Gigi',
                'bank' => 'SYARIAH MANDIRI',
                'status' => '',
                'tindakan' => '',
            ],
            [
                'kode' => '24',
                'hal' => 'Penagihan Biaya Potong Gaji Karyawan RS LNG Badak',
                'jenis_tagihan' => '',
                'deskripsi' => '',
                'ket_pembayaran' => 'Vaksinasi',
                'layanan_id' => null,
                'status' => '',
                'unit_dokter' => 'Radiologi',
                'kota' => '',
                'rumah_sakit' => '',
                'spesialisasi' => 'Sp. Kulit & Kelamin',
                'bank' => '',
                'status' => '',
                'tindakan' => '',
            ]
        ];
        \App\Models\PerihalTagihan::insert($perihalTagihan);
    }
}
